### ISSUE TITLE
URGENT: Sub title on argosdb.org page must be removed.

### ISSUE THREAD

**Issue by steph-sing** [FDA-ARGOS2/argosdb#21]
This was an urgent issue in Dec 2022, and I see that the Production site has still not been updated. Please removed 'The Regulatory-Grade Database for Infectious Disease Detection' subtitle from the Home page ASAP. Thank you

**Comment by Reeya123** [comment]
@steph-sing Hello Stephanie. Robel mistakenly pushed the previous code that had issues. I have pushed the updated code again (in which the subtitle has already been removed). It's in the process of being pushed to production.

**Comment by steph-sing** [comment]
This has still not been completed. Who is this task with now, and can you point me to the ticket?
